version: "3.6"
services:
  backend:
    image: backend:latest
    restart: unless-stopped
  frontend:
    depends_on:
      - backend
    environment:
      - BACKEND_HOSTNAME=backend
    image: frontend:latest
    ports:
      - "80:8080"
    restart: unless-stopped